version: '3.3'
networks:
  - choco-repo
services:
  choco-repo:
    image: choco-repo
    container_name: choco-repo
    restart: unless-stopped
    environment:
      - DOMAINS="chocolatey.my.domain.net"
      - VHOST1="chocolatey.my.domain.net"
      - WEBMASTER_MAIL="Me@my.domain.net"
      - STAGING="false"
      - SSLCRT=fullchain.pem
      - SSLCRT=privkey.pem
    build:
      context: .
    #cpus: 2
    #mem_limit: 1024m
    #mem_reservation: 800M
    dns:
      - 1.1.1.1
    ports:
      - 8090:80
      - 8091:443
    volumes:
      - /choco/:/app/phpnuget/data/
    networks:
      - default
